spring.application.name=AIStockConcluder

openai.api.key=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
alpha.vantage.key=S9O0C6AEYXKMN6TF