spring.application.name=AIStockConcluder

openai.api.key=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
alpha.vantage.key=S9O0C6AEYXKMN6TF