spring.application.name=AIStockConcluder

openai.api.key=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
alpha.vantage.key=S9O0C6AEYXKMN6TF