package com.example.aistockconcluder.dto;

import com.fasterxml.jackson.annotation.*;

import javax.annotation.processing.Generated;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
//@JsonInclude, prohibits null values from being included in the outgoing JSON, which keeps the request clean.
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
        "model",
        "messages",
        "n",
        "temperature",
        "max_tokens",
        "stream",
        "presence_penalty"
})

//This class contains properties to set ChatGPT API attributes.
//@Generated("jsonschema2pojo"), is a marker annotation. It indicates that the class is automatically generated by a tool, namely Jsonschema2pojo in this case.
@Generated("jsonschema2pojo")
public class ChatRequest {
    //https://codefarm0.medium.com/why-you-should-use-jsonproperty-and-jsonalias-together-in-jackson-6764d7026c7b
    //@JsonProperty, defines the 'official' JSON name for a field. This property of JSON is related with the field name in the application. The value always stayes the same? These names are valid in both serialization and desirializaition.
    //@JsonAlias, defines the extra 'valid' JSON names for a field in application. This is only for reading from JSON(Desirialzition).

    //model, is used to set the spefic model, and what overall model it implements, such as completion model, and/or chat model.
    @JsonProperty("model")
    private String model;

    @JsonProperty("messages")
    private List<Message> messages;

    @JsonProperty("n")
    private Integer n;

    @JsonProperty("temperature")
    private Integer temperature;

    @JsonProperty("max_tokens")
    private Integer maxTokens;

    @JsonProperty("stream")
    private Boolean stream;

    @JsonProperty("presence_penalty")
    private Integer presencePenalty;

    @JsonIgnore
    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();


    //Getters
    @JsonProperty("model")
    public String getModel() {
        return model;
    }

    @JsonProperty("messages")
    public List<Message> getMessages() {
        return messages;
    }

    @JsonProperty("n")
    public Integer getN() {
        return n;
    }

    @JsonProperty("temperature")
    public Integer getTemperature() {
        return temperature;
    }

    @JsonProperty("max_tokens")
    public Integer getMaxTokens() {
        return maxTokens;
    }

    @JsonProperty("stream")
    public Boolean getStream() {
        return stream;
    }

    @JsonProperty("presence_penalty")
    public Integer getPresencePenalty() {
        return presencePenalty;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return additionalProperties;
    }

    //Setters


    @JsonProperty("model")
    public void setModel(String model) {
        this.model = model;
    }
    @JsonProperty("messages")
    public void setMessages(List<Message> messages) {
        this.messages = messages;
    }
    @JsonProperty("n")
    public void setN(Integer n) {
        this.n = n;
    }
    @JsonProperty("temperature")
    public void setTemperature(Integer temperature) {
        this.temperature = temperature;
    }
    @JsonProperty("max_tokens")
    public void setMaxTokens(Integer maxTokens) {
        this.maxTokens = maxTokens;
    }
    @JsonProperty("stream")
    public void setStream(Boolean stream) {
        this.stream = stream;
    }
    @JsonProperty("presence_penalty")
    public void setPresencePenalty(Integer presencePenalty) {
        this.presencePenalty = presencePenalty;
    }
    @JsonAnySetter
    public void setAdditionalProperties(Map<String, Object> additionalProperties) {
        this.additionalProperties = additionalProperties;
    }

}
